//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashray
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentreRegistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CentreRegistration()
        {
            this.PatientInfoes = new HashSet<PatientInfo>();
        }
    
        public int CentreId { get; set; }
        public string CentreName { get; set; }
        public string ContactPerson { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public Nullable<int> BedCount { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> StateId { get; set; }
    
        public virtual LocationDetail LocationDetail { get; set; }
        public virtual StateDetail StateDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientInfo> PatientInfoes { get; set; }
    }
}
