//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashray
{
    using System;
    using System.Collections.Generic;
    
    public partial class CenterRoomInfo
    {
        public int CenterRoomId { get; set; }
        public Nullable<int> CenterId { get; set; }
        public string RoomNumber { get; set; }
        public string RoomType { get; set; }
    }
}
