//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashray
{
    using System;
    using System.Collections.Generic;
    
    public partial class CenterRoomBedInfo
    {
        public int CenterRoomBedInfoId { get; set; }
        public Nullable<int> CenterRoomId { get; set; }
        public string BedType { get; set; }
        public string BedNumber { get; set; }
    }
}
